name: .NET Core

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Submodule Init
      run: git submodule init --
    - name: Submodule Update
      run: git submodule update --
    - name: Submodule Checkout
      run: git submodule foreach git checkout master
    - name: Submodule Pull
      run: git submodule foreach git pull
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework netcoreapp3.1
    - name: Test
      run: dotnet test ./JSSoft.Library.Commands/ --no-restore --verbosity normal --framework netcoreapp3.1
