name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore Ntreev.Library.Commands
    - name: Build
      run: dotnet build Ntreev.Library.Commands --configuration Release --no-restore --framework netcoreapp3.1
    - name: Test
      run: dotnet test Ntreev.Library.Commands --no-restore --verbosity normal --framework netcoreapp3.1
