name: Check Typos

on: 
  pull_request:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crate-ci/typos@v1.22.9
        with:
          config: .github/workflows/typos.toml
